include:
  - board: nice_nano
    shield: charybdis_left      # ← 中央（ホスト/BLE名が出る側）
    snippet: studio-rpc-usb-uart       # ← Studio用RPCをUSB/UARTで有効化
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n  # ← Studio機能ON
  - board: nice_nano
    shield: charybdis_right   # ← 反対側）
